#define BaseVIconID 79000

class Life_HUD_vehicleTags {
	idd = -1;
	duration = 1e+011;
	name = "Life_HUD_vehicleTags";
	onLoad = "uiNamespace setVariable['Life_HUD_vehicleTags',_this select 0]";
	objects[] = {};
	
	class controls
	{
		class BaseIcon
		{
			idc = -1;
			type = 13;
			style = 0;
			colorText[] = {1,1,1,1};
			colorBackground[] = {0,0,0,0};
			font = "PuristaMedium";
			text = "";
			size = 0.04;
			shadow = 1.5;
			w = 0; h = 0;
			x = 0.1; y = 0.1;
		};
		
		class v1 : BaseIcon {idc = BaseVIconID;};
		class v2 : BaseIcon {idc = BaseVIconID + 1;};
		class v3 : BaseIcon {idc = BaseVIconID + 2;};
		class v4 : BaseIcon {idc = BaseVIconID + 3;};
		class v5 : BaseIcon {idc = BaseVIconID + 4;};
		class v6 : BaseIcon {idc = BaseVIconID + 5;};
		class v7 : BaseIcon {idc = BaseVIconID + 6;};
		class v8 : BaseIcon {idc = BaseVIconID + 7;};
		class v9 : BaseIcon {idc = BaseVIconID + 8;};
		class v10 : BaseIcon {idc = BaseVIconID + 9;};
		class v11 : BaseIcon {idc = BaseVIconID + 10;};
		class v12 : BaseIcon {idc = BaseVIconID + 11;};
		class v13 : BaseIcon {idc = BaseVIconID + 12;};
		class v14 : BaseIcon {idc = BaseVIconID + 13;};
		class v15 : BaseIcon {idc = BaseVIconID + 14;};
		class v16 : BaseIcon {idc = BaseVIconID + 15;};
		class v17 : BaseIcon {idc = BaseVIconID + 16;};
		class v18 : BaseIcon {idc = BaseVIconID + 17;};
		class v19 : BaseIcon {idc = BaseVIconID + 18;};
		class v20 : BaseIcon {idc = BaseVIconID + 19;};
		class v21 : BaseIcon {idc = BaseVIconID + 20;};
		class v22 : BaseIcon {idc = BaseVIconID + 21;};
		class v23 : BaseIcon {idc = BaseVIconID + 22;};
		class v24 : BaseIcon {idc = BaseVIconID + 23;};
		class v25 : BaseIcon {idc = BaseVIconID + 24;};
		class v26 : BaseIcon {idc = BaseVIconID + 25;};
		class v27 : BaseIcon {idc = BaseVIconID + 26;};
		class v28 : BaseIcon {idc = BaseVIconID + 27;};
		class v29 : BaseIcon {idc = BaseVIconID + 28;};
		class v30 : BaseIcon {idc = BaseVIconID + 29;};
		class v31 : BaseIcon {idc = BaseVIconID + 30;};
		class v32 : BaseIcon {idc = BaseVIconID + 31;};
		class v33 : BaseIcon {idc = BaseVIconID + 32;};
		class v34 : BaseIcon {idc = BaseVIconID + 33;};
		class v35 : BaseIcon {idc = BaseVIconID + 34;};
		class v36 : BaseIcon {idc = BaseVIconID + 35;};
		class v37 : BaseIcon {idc = BaseVIconID + 36;};
		class v38 : BaseIcon {idc = BaseVIconID + 37;};
		class v39 : BaseIcon {idc = BaseVIconID + 38;};
		class v40 : BaseIcon {idc = BaseVIconID + 39;};
		class v41 : BaseIcon {idc = BaseVIconID + 40;};
		class v42 : BaseIcon {idc = BaseVIconID + 41;};
		class v43 : BaseIcon {idc = BaseVIconID + 42;};
		class v44 : BaseIcon {idc = BaseVIconID + 43;};
		class v45 : BaseIcon {idc = BaseVIconID + 44;};
		class v46 : BaseIcon {idc = BaseVIconID + 45;};
		class v47 : BaseIcon {idc = BaseVIconID + 46;};
		class v48 : BaseIcon {idc = BaseVIconID + 47;};
		class v49 : BaseIcon {idc = BaseVIconID + 48;};
		class v50 : BaseIcon {idc = BaseVIconID + 49;};
		class v51 : BaseIcon {idc = BaseVIconID + 50;};
		class v52 : BaseIcon {idc = BaseVIconID + 51;};
		class v53 : BaseIcon {idc = BaseVIconID + 52;};
		class v54 : BaseIcon {idc = BaseVIconID + 53;};
		class v55 : BaseIcon {idc = BaseVIconID + 54;};
		class v56 : BaseIcon {idc = BaseVIconID + 55;};
		class v57 : BaseIcon {idc = BaseVIconID + 56;};
		class v58 : BaseIcon {idc = BaseVIconID + 57;};
		class v59 : BaseIcon {idc = BaseVIconID + 58;};
		class v60 : BaseIcon {idc = BaseVIconID + 59;};
		class v61 : BaseIcon {idc = BaseVIconID + 60;};
		class v62 : BaseIcon {idc = BaseVIconID + 61;};
		class v63 : BaseIcon {idc = BaseVIconID + 62;};
		class v64 : BaseIcon {idc = BaseVIconID + 63;};
		class v65 : BaseIcon {idc = BaseVIconID + 64;};
		class v66 : BaseIcon {idc = BaseVIconID + 65;};
		class v67 : BaseIcon {idc = BaseVIconID + 66;};
		class v68 : BaseIcon {idc = BaseVIconID + 67;};
		class v69 : BaseIcon {idc = BaseVIconID + 68;};
		class v70 : BaseIcon {idc = BaseVIconID + 69;};
		class v71 : BaseIcon {idc = BaseVIconID + 70;};
		class v72 : BaseIcon {idc = BaseVIconID + 71;};
		class v73 : BaseIcon {idc = BaseVIconID + 72;};
		class v74 : BaseIcon {idc = BaseVIconID + 73;};
		class v75 : BaseIcon {idc = BaseVIconID + 74;};
		class v76 : BaseIcon {idc = BaseVIconID + 75;};
		class v77 : BaseIcon {idc = BaseVIconID + 76;};
		class v78 : BaseIcon {idc = BaseVIconID + 77;};
		class v79 : BaseIcon {idc = BaseVIconID + 78;};
		class v80 : BaseIcon {idc = BaseVIconID + 79;};
		class v81 : BaseIcon {idc = BaseVIconID + 80;};
		class v82 : BaseIcon {idc = BaseVIconID + 81;};
		class v83 : BaseIcon {idc = BaseVIconID + 82;};
		class v84 : BaseIcon {idc = BaseVIconID + 83;};
		class v85 : BaseIcon {idc = BaseVIconID + 84;};
		class v86 : BaseIcon {idc = BaseVIconID + 85;};
		class v87 : BaseIcon {idc = BaseVIconID + 86;};
		class v88 : BaseIcon {idc = BaseVIconID + 87;};
		class v89 : BaseIcon {idc = BaseVIconID + 88;};
		class v90 : BaseIcon {idc = BaseVIconID + 89;};
		class v91 : BaseIcon {idc = BaseVIconID + 90;};
		class v92 : BaseIcon {idc = BaseVIconID + 91;};
		class v93 : BaseIcon {idc = BaseVIconID + 92;};
		class v94 : BaseIcon {idc = BaseVIconID + 93;};
		class v95 : BaseIcon {idc = BaseVIconID + 94;};
		class v96 : BaseIcon {idc = BaseVIconID + 95;};
		class v97 : BaseIcon {idc = BaseVIconID + 96;};
		class v98 : BaseIcon {idc = BaseVIconID + 97;};
		class v99 : BaseIcon {idc = BaseVIconID + 98;};
		class v100 : BaseIcon {idc = BaseVIconID + 99;};
		class v101 : BaseIcon {idc = BaseVIconID + 100;};
		class v102 : BaseIcon {idc = BaseVIconID + 101;};
		class v103 : BaseIcon {idc = BaseVIconID + 102;};
		class v104 : BaseIcon {idc = BaseVIconID + 103;};
		class v105 : BaseIcon {idc = BaseVIconID + 104;};
		class v106 : BaseIcon {idc = BaseVIconID + 105;};
		class v107 : BaseIcon {idc = BaseVIconID + 106;};
		class v108 : BaseIcon {idc = BaseVIconID + 107;};
		class v109 : BaseIcon {idc = BaseVIconID + 108;};
		class v110 : BaseIcon {idc = BaseVIconID + 109;};
	};
};